## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [12]:
from sklearn.model_selection import train_test_split, KFold
import pandas as pd

X_1 = X[:40]
X_0 = X[40:]
y_1 = y[:40]
y_0 = y[40:]
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1, y_1, test_size=10)
X_0_train, X_0_test, y_0_train, y_0_test = train_test_split(X_0, y_0, test_size=10)
X_train = np.concatenate([X_1_train, X_0_train])
X_test = np.concatenate([X_1_test, X_0_test])
y_train = np.concatenate([y_1_train, y_0_train])
y_test = np.concatenate([y_1_test, y_0_test])
X_test, y_test

(array([[195, 196, 197, 198, 199],
        [190, 191, 192, 193, 194],
        [135, 136, 137, 138, 139],
        [ 90,  91,  92,  93,  94],
        [  5,   6,   7,   8,   9],
        [185, 186, 187, 188, 189],
        [130, 131, 132, 133, 134],
        [ 95,  96,  97,  98,  99],
        [ 70,  71,  72,  73,  74],
        [ 45,  46,  47,  48,  49],
        [670, 671, 672, 673, 674],
        [870, 871, 872, 873, 874],
        [745, 746, 747, 748, 749],
        [875, 876, 877, 878, 879],
        [845, 846, 847, 848, 849],
        [420, 421, 422, 423, 424],
        [530, 531, 532, 533, 534],
        [635, 636, 637, 638, 639],
        [250, 251, 252, 253, 254],
        [550, 551, 552, 553, 554]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]))